package com.mycompany.agenciafiscalpresentacion.GUI;

import excepciones.NegocioException;
import iBo.iRegistrarLicenciaBO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import negocioDTO.PersonaDTO;

/**
 *
 * @author caarl
 */
public class MenuJpanel extends javax.swing.JPanel {

    protected static List<PersonaDTO> personasRegistradas;
    /**
     * Creates new form PrincipalJpanel
     */
    public MenuJpanel() {
        initComponents();
        personasRegistradas=new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnModuloLicencias = new javax.swing.JButton();
        btnModuloPlacas = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnInsertarUsuarios = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(111, 18, 18));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setBackground(new java.awt.Color(138, 47, 47));

        jLabel2.setFont(new java.awt.Font("Avenir Next", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gobierno del estado de sonora");
        jPanel3.add(jLabel2);

        jPanel1.add(jPanel3);

        jPanel2.setBackground(new java.awt.Color(138, 47, 47));

        jLabel3.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Control de placas y licencias automovílisticas");
        jPanel2.add(jLabel3);

        jPanel1.add(jPanel2);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 80));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Avenir Next", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Módulos de Información");
        jPanel4.add(jLabel1);

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 640, 60));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 100));
        jPanel5.setLayout(new java.awt.GridLayout(2, 2, 50, 20));

        btnModuloLicencias.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnModuloLicencias.setText("Licencias");
        btnModuloLicencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloLicenciasActionPerformed(evt);
            }
        });
        jPanel5.add(btnModuloLicencias);

        btnModuloPlacas.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnModuloPlacas.setText("Placas para automovil");
        btnModuloPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloPlacasActionPerformed(evt);
            }
        });
        jPanel5.add(btnModuloPlacas);

        btnConsultas.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnConsultas.setText("Consultas");
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });
        jPanel5.add(btnConsultas);

        btnReportes.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel5.add(btnReportes);

        jPanel6.add(jPanel5);

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 640, 110));

        jPanel7.setBackground(new java.awt.Color(138, 47, 47));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 15));

        btnInsertarUsuarios.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnInsertarUsuarios.setText("Insertar registros usuarios");
        btnInsertarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarUsuariosActionPerformed(evt);
            }
        });
        jPanel7.add(btnInsertarUsuarios);

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 640, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btnModuloLicenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloLicenciasActionPerformed
        // Mensaje e información personalizada
        String mensaje = "Tipo de operación";
        String titulo = "Seleccione una opcion";
        Object[] opciones = { "Tramitar licencia", "Cancelar licencia", "Cancelar" }; // Texto personalizado de los botones

        // Mostrar el diálogo con botones personalizados
        int opcionSeleccionada = JOptionPane.showOptionDialog(null, mensaje, titulo, JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

        // Verificar la opción seleccionada por el usuario
        switch (opcionSeleccionada) {
            case 0:
                // Seleccionó "Tramitar licencia"
                System.out.println("Tramitar licencia");
                ((Ventanas) SwingUtilities.getWindowAncestor(MenuJpanel.this)).mostrarVentana("ModuloLicenciasJpanel");
                break;
            case 1:
                // Seleccionó "Cancelar licencia"
                System.out.println("Cancelar licencia");
                ((Ventanas) SwingUtilities.getWindowAncestor(MenuJpanel.this)).mostrarVentana("ModuloBajaLicencia");
                break;
            case 2:
                // Seleccionó "Cancelar"
                System.out.println("Cancelar");
                break;
            default:
                // El usuario cerró el diálogo sin seleccionar ninguna opción
                System.out.println("El usuario ha cerrado el diálogo sin seleccionar ninguna opción");
                break;
        }
    }//GEN-LAST:event_btnModuloLicenciasActionPerformed

    private void btnModuloPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloPlacasActionPerformed
        // TODO add your handling code here:
//        try {
//            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
//                | UnsupportedLookAndFeelException e) {
//            e.printStackTrace();
//        }

        
        desplegarOperacionesPlacas();
        //((Ventanas) SwingUtilities.getWindowAncestor(MenuJpanel.this)).mostrarVentana("ModuloLicenciasJpanel");
    }//GEN-LAST:event_btnModuloPlacasActionPerformed

    private void desplegarOperacionesPlacas() {
        // Mensaje e información personalizada
        String mensaje = "Tipo de operación";
        String titulo = "Seleccione una opcion";
        Object[] opciones = { "Dar de alta", "Dar de baja", "Cancelar" }; // Texto personalizado de los botones

        // Mostrar el diálogo con botones personalizados
        int opcionSeleccionada = JOptionPane.showOptionDialog(null, mensaje, titulo, JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

        // Verificar la opción seleccionada por el usuario
        switch (opcionSeleccionada) {
            case 0:
                // Seleccionó "Dar de alta"
                System.out.println("Dar de alta");
                desplegarOpcionesAltaPlacas();
                break;
            case 1:
                // Seleccionó "Dar de baja"
                System.out.println("Dar de baja");
                ((Ventanas) SwingUtilities.getWindowAncestor(MenuJpanel.this)).mostrarVentana("ModuloBajaPlacas");
                break;
            case 2:
                // Seleccionó "Cancelar"
                System.out.println("cancelar");
                break;
            default:
                // El usuario cerró el diálogo sin seleccionar ninguna opción
                System.out.println("El usuario ha cerrado el diálogo sin seleccionar ninguna opción");
                break;
        }
    }
    
    private void desplegarOpcionesAltaPlacas() {
        // Mensaje e información personalizada
        String mensaje = "Tipo de auto";
        String titulo = "Seleccione una opcion";
        Object[] opciones = { "Nuevo", "Usado", "Cancelar" }; // Texto personalizado de los botones

        // Mostrar el diálogo con botones personalizados
        int opcionSeleccionada = JOptionPane.showOptionDialog(null, mensaje, titulo, JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

        // Verificar la opción seleccionada por el usuario
        switch (opcionSeleccionada) {
            case 0:
                // Seleccionó "nuevo"
                System.out.println("auto nuevo");
                ((Ventanas) SwingUtilities.getWindowAncestor(MenuJpanel.this)).mostrarVentana("ModuloPlacasAutoNuevo");
                break;
            case 1:
                // Seleccionó "usado"
                System.out.println("auto usado");
                ((Ventanas) SwingUtilities.getWindowAncestor(MenuJpanel.this)).mostrarVentana("ModuloPlacasAutoUsado");
                break;
            case 2:
                // Seleccionó "Cancelar"
                System.out.println("cancelar");
                break;
            default:
                // El usuario cerró el diálogo sin seleccionar ninguna opción
                System.out.println("El usuario ha cerrado el diálogo sin seleccionar ninguna opción");
                break;
        }
    }
    
    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        ((Ventanas) SwingUtilities.getWindowAncestor(MenuJpanel.this)).mostrarVentana("ModuloConsultas");
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        ((Ventanas) SwingUtilities.getWindowAncestor(MenuJpanel.this)).mostrarVentana("ModuloReportes");
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnInsertarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarUsuariosActionPerformed
        // TODO add your handling code here:
        obtenerPersonasAgregadas();
    }//GEN-LAST:event_btnInsertarUsuariosActionPerformed

    private void obtenerPersonasAgregadas(){
        try{
            personasRegistradas=Ventanas.registrarLicencia.obtenerPersonasRegistradas();
        }catch(NegocioException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnInsertarUsuarios;
    private javax.swing.JButton btnModuloLicencias;
    private javax.swing.JButton btnModuloPlacas;
    private javax.swing.JButton btnReportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
